export const siteContent = {
  heroVideo: "assets/farmacia.mp4",
  promotions: [
    {
      type: "video",
      src: "assets/antiacido.mp4",
      label: "Video informativo",
      name: "Cuidado digestivo",
      note: "Conoce opciones disponibles para el bienestar digestivo.",
    },
    {
      type: "video",
      src: "assets/neuromix.mp4",
      label: "Video informativo",
      name: "Vitaminas y bienestar",
      note: "Productos pensados para complementar el cuidado cotidiano.",
    },
    {
      type: "video",
      src: "assets/Los%20antibi%C3%B3ticos.mp4",
      label: "Video informativo",
      name: "Uso responsable de antibióticos",
      note: "Información educativa sobre la importancia de utilizar antibióticos solo bajo orientación profesional.",
    },
    {
      type: "image",
      src: "assets/promocion1.png",
      label: "Novedades",
      name: "Multivitaminas",
      alt: "Promoción de multivitaminas disponibles en Farmacia Atenas",
      note: "Consulta presentaciones, disponibilidad y precio.",
    },
    {
      type: "image",
      src: "assets/analgesico.png",
      label: "Categoría",
      name: "Analgésicos y antipiréticos",
      alt: "Productos de la categoría de analgésicos y antipiréticos",
      note: "Solicita orientación sobre presentaciones disponibles.",
    },
    {
      type: "image",
      src: "assets/antihistaminicos.png",
      label: "Categoría",
      name: "Antihistamínicos",
      alt: "Productos de la categoría de antihistamínicos",
      note: "Disponibilidad sujeta a inventario y condiciones de venta.",
    },
    {
      type: "image",
      src: "assets/botiquin.png",
      label: "Bienestar familiar",
      name: "Botiquín en casa",
      alt: "Productos recomendados para organizar un botiquín doméstico",
      note: "Encuentra productos esenciales para el cuidado familiar.",
    },
    {
      type: "image",
      src: "assets/festal.png",
      label: "Producto destacado",
      name: "Festal",
      alt: "Pieza informativa del producto Festal",
      note: "Consulta disponibilidad y condiciones de venta.",
    },
    {
      type: "image",
      src: "assets/DOL.jpeg",
      label: "Producto destacado",
      name: "Opciones para el dolor",
      alt: "Pieza promocional de productos para el alivio del dolor",
      note: "Pregunta por presentaciones y precio vigente.",
    },
    {
      type: "image",
      src: "assets/GLIMAG.jpeg",
      label: "Producto destacado",
      name: "GliMag",
      alt: "Pieza promocional del suplemento GliMag",
      note: "Consulta disponibilidad y precio vigente.",
    },
    {
      type: "image",
      src: "assets/MAGNO.jpeg",
      label: "Producto destacado",
      name: "Magno",
      alt: "Pieza promocional del producto Magno",
      note: "Consulta disponibilidad y precio vigente.",
    },
  ],
};
